language: csharp
solution: Jira.WallboardScreensaver.sln

env:
  - CONFIGURATION=Release

script:
  - msbuild /p:Configuration=$CONFIGURATION
  - nunit-console ./*/bin/*/*.Tests.dll
  - msbuild Jira.WallboardScreensaver /p:Configuration=$CONFIGURATION /t:Package

addons:
  apt:
    packages:
      - nunit-console